name: Run Unit Tests - CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
      - '.dockerignore'
      - '.python-version'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: |
        uv run pytest tests
        
    - name: Build documentation
      run: |
        cd docs
        uv run mkdocs build