name: Publish Python Package

on:
    push:
        tags:
            - 'release/*'

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: release # This environment can publish to PyPI
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'

        - name: Install uv
          run: |
            python -m pip install --upgrade pip
            pip install uv

        - name: Build package
          run: |
            uv build

        - name: Publish package
          run: |
            uv publish