name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        chmod +x create_env.sh
        ./create_env.sh

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests
        
    - name: Build documentation
      run: |
        source .venv/bin/activate
        cd docs
        mkdocs build

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4